### ISSUE TITLE
Caddyfile detecting "}" as duplicate global options

### ISSUE THREAD

**Issue by U5B** [matthewpi/vscode-caddyfile-support#254] opened 2022-09-06 19:16 UTC
**System Information**
* Operating System: Ubuntu 22.04
* Extension Version: 0.2.0
* VSCode Version: 1.70
* `caddy` Version: 2.5.2

**Describe the bug**
Caddyfile detects the "}" as a duplicate.

**Steps to Reproduce**
Create two global options that use "{" and "}" on different lines.

**Expected Behavior**
No error should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/56985400/188720060-49eef1c4-350c-4f0c-b179-0b3e1961a6bf.png)

**Additional Context**

**Comment by francislavoie** [comment] 2022-09-06 19:19
Works fine for me. I think the problem is that `ne` you have in there, which makes the `{` token immediately before it not match as a valid opening brace token.

**Comment by U5B** [comment] 2022-09-07 16:33
hmm I added a newline to the top and that removed the error
I removed `ne` (that wasn't supposed to be there anyway)

This is what I have now
```
{
	servers {
		log_credentials
		protocol {
			strict_sni_host on
		}
	}
	log {
		output file /home/bot/web/caddy/logs/caddy.log
		format json {
			time_format unix_milli_float
			duration_format seconds
		}
		level INFO
		include http.log.access
	}
}
```

**Comment by matthewpi** [comment] 2022-10-11 21:37
This should be resolved by https://github.com/matthewpi/vscode-caddyfile-support/commit/ee91c9af970d6fea298cfd4bcf877413656f1714

**Closed by matthewpi** 2022-10-11 21:37 UTC
Labels: 🐛 type/bug
